name: Mayhem for API
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Start your API
      id: start
      run: |
        pip3 install -r requirements.txt
        python3 app.py &
        sleep 5
        curl http://localhost:5000

    - name: Run Mayhem for API to check for vulnerabilities
      id: mapi
      if: steps.start.outcome == 'success'
      uses: ForAllSecure/mapi-action@v1.3.0
      continue-on-error: true
      with:
        mapi-token: ${{ secrets.MAPI_TOKEN }}
        api-url: http://localhost:5000
        api-spec: openapi_specs/openapi3.yml
        sarif-report: mapi.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: mapi.sarif

    - name: Fail Mayhem finds bugs
      if: steps.mapi.outcome == 'failure'
      run: exit 1
